// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pdi.Full.Micro.Service.Repositories.Contexts;

#nullable disable

namespace Pdi.Full.Micro.Service.WebApi.Migrations
{
    [DbContext(typeof(FullServiceDbContext))]
    [Migration("20231115114058_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pdi.Full.Micro.Service.Entities.Models.ItemDaVenda", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualDeDesconto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequencial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("ProdutoId", "VendaId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensDasVendas");
                });

            modelBuilder.Entity("Pdi.Full.Micro.Service.Entities.Models.Produto", b =>
                {
                    b.Property<long>("Sequencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeEmEstoque")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequencial");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Pdi.Full.Micro.Service.Entities.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDaVenda")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Pdi.Full.Micro.Service.Entities.Models.ItemDaVenda", b =>
                {
                    b.HasOne("Pdi.Full.Micro.Service.Entities.Models.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdi.Full.Micro.Service.Entities.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
